// internal/controller/task_controller.go
package controller

import (
    "errors"
    "net/http"
    "strings"

    "github.com/Perlishnov/TODO_APP/internal/models"
    "github.com/Perlishnov/TODO_APP/internal/service"
    "github.com/gin-gonic/gin"
    "github.com/sirupsen/logrus"
)

type TaskController struct {
    taskService service.TaskService
    logger      *logrus.Logger
}

func NewTaskController(taskService service.TaskService, logger *logrus.Logger) *TaskController {
    return &TaskController{
        taskService: taskService,
        logger:      logger,
    }
}

func (ctrl *TaskController) RegisterRoutes(router *gin.RouterGroup, authMiddleware gin.HandlerFunc) {
    tasks := router.Group("/tasks")
    tasks.Use(authMiddleware)
    {
        tasks.POST("/", ctrl.Create)
        tasks.GET("/", ctrl.List)
        tasks.GET("/:id", ctrl.GetById)
        tasks.PUT("/:id", ctrl.Update)
        tasks.DELETE("/:id", ctrl.Delete)
    }
}

// Create godoc
// @Summary      Create a new task
// @Description  Creates a task for the authenticated user
// @Tags         tasks
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        request body models.CreateTaskRequest true "Task details"
// @Success      201 {object} map[string]string "message"
// @Failure      400 {object} map[string]string "invalid input"
// @Failure      401 {object} map[string]string "unauthorized"
// @Failure      409 {object} map[string]string "too many in-progress tasks"
// @Router       /tasks [post]
func (ctrl *TaskController) Create(c *gin.Context) {
    userID, exists := c.Get("userID")
    if !exists {
        ctrl.logger.Warn("userID missing from context")
        c.JSON(http.StatusUnauthorized, gin.H{"error": "unauthorized"})
        return
    }
    userIDStr, ok := userID.(string)
    if !ok || userIDStr == "" {
        ctrl.logger.Error("invalid userID type or empty")
        c.JSON(http.StatusInternalServerError, gin.H{"error": "invalid user context"})
        return
    }

    var req models.CreateTaskRequest
    if err := c.ShouldBindJSON(&req); err != nil {
        ctrl.logger.WithError(err).Warn("invalid create task request")
        c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request body"})
        return
    }

    // Build the Task object (ID will be generated by the DAO)
    task := &models.Task{
        UserID:      userIDStr,
        Title:       req.Title,
        Description: req.Description,
        Status:      req.Status,
    }

    if err := ctrl.taskService.Create(c.Request.Context(), task); err != nil {
        ctrl.logger.WithError(err).Error("create task failed")
        if strings.Contains(err.Error(), "cannot have more than 3 tasks in progress") {
            c.JSON(http.StatusConflict, gin.H{"error": err.Error()})
            return
        }
        c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
        return
    }

    // Because Create does not return the created task, we return a simple success message.
    // Optionally you could fetch the task by its generated ID if you need the full object.
    c.JSON(http.StatusCreated, gin.H{"message": "task created", "id": task.ID})
}

// List godoc
// @Summary      List user's tasks
// @Description  Returns paginated list of tasks for the authenticated user
// @Tags         tasks
// @Produce      json
// @Security     BearerAuth
// @Param        status query string false "Filter by status (pending, in_progress, done)"
// @Param        search query string false "Search in title or description"
// @Param        page query int false "Page number (default 1)"
// @Param        page_size query int false "Items per page (default 10, max 100)"
// @Param        sort_by query string false "Sort field (title, created_at, updated_at, status)"
// @Param        sort_dir query string false "Sort direction (asc, desc)"
// @Success      200 {object} map[string]interface{}
// @Failure      401 {object} map[string]string "unauthorized"
// @Router       /tasks [get]
func (ctrl *TaskController) List(c *gin.Context) {
    userID, _ := c.Get("userID")
    userIDStr := userID.(string)

    var filter models.TaskFilter
    if err := c.ShouldBindQuery(&filter); err != nil {
        ctrl.logger.WithError(err).Warn("invalid query parameters")
        c.JSON(http.StatusBadRequest, gin.H{"error": "invalid query parameters"})
        return
    }

    tasks, err := ctrl.taskService.List(c.Request.Context(), &filter, userIDStr)
    if err != nil {
        ctrl.logger.WithError(err).Error("list tasks failed")
        c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to retrieve tasks"})
        return
    }

    c.JSON(http.StatusOK, gin.H{
        "tasks":     tasks,
        "page":      filter.Page,
        "page_size": filter.PageSize,
    })
}

// GetById godoc
// @Summary      Get a task by ID
// @Description  Returns a single task if the user owns it
// @Tags         tasks
// @Produce      json
// @Security     BearerAuth
// @Param        id path string true "Task ID"
// @Success      200 {object} models.Task
// @Failure      401 {object} map[string]string "unauthorized"
// @Failure      403 {object} map[string]string "access denied"
// @Failure      404 {object} map[string]string "not found"
// @Router       /tasks/{id} [get]
func (ctrl *TaskController) GetById(c *gin.Context) {
    taskID := c.Param("id")
    if taskID == "" {
        c.JSON(http.StatusBadRequest, gin.H{"error": "invalid task ID"})
        return
    }

    userID, _ := c.Get("userID")
    userIDStr := userID.(string)

    task, err := ctrl.taskService.GetById(c.Request.Context(), taskID, userIDStr)
    if err != nil {
        if errors.Is(err, errors.New("task not found")) {
            c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
            return
        }
        if err.Error() == "access denied" {
            c.JSON(http.StatusForbidden, gin.H{"error": err.Error()})
            return
        }
        ctrl.logger.WithError(err).Error("get task failed")
        c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to get task"})
        return
    }

    c.JSON(http.StatusOK, task)
}

// Update godoc
// @Summary      Update a task
// @Description  Updates an existing task (owner only)
// @Tags         tasks
// @Accept       json
// @Produce      json
// @Security     BearerAuth
// @Param        id path string true "Task ID"
// @Param        request body models.UpdateTaskRequest true "Updated fields"
// @Success      200 {object} map[string]string "message"
// @Failure      400 {object} map[string]string "invalid input"
// @Failure      401 {object} map[string]string "unauthorized"
// @Failure      403 {object} map[string]string "access denied"
// @Failure      404 {object} map[string]string "not found"
// @Failure      409 {object} map[string]string "too many in-progress tasks"
// @Router       /tasks/{id} [put]
func (ctrl *TaskController) Update(c *gin.Context) {
    taskID := c.Param("id")
    if taskID == "" {
        c.JSON(http.StatusBadRequest, gin.H{"error": "invalid task ID"})
        return
    }

    userID, _ := c.Get("userID")
    userIDStr := userID.(string)

    var req models.UpdateTaskRequest
    if err := c.ShouldBindJSON(&req); err != nil {
        ctrl.logger.WithError(err).Warn("invalid update request")
        c.JSON(http.StatusBadRequest, gin.H{"error": "invalid request body"})
        return
    }

    task := &models.Task{
        ID: taskID,
    }
    if req.Title != nil {
        task.Title = *req.Title
    }
    if req.Description != nil {
        task.Description = *req.Description
    }
    if req.Status != nil {
        task.Status = *req.Status
    }

    err := ctrl.taskService.Update(c.Request.Context(), task, userIDStr)
    if err != nil {
        switch {
        case strings.Contains(err.Error(), "not found"):
            c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
        case strings.Contains(err.Error(), "access denied"):
            c.JSON(http.StatusForbidden, gin.H{"error": err.Error()})
        case strings.Contains(err.Error(), "cannot have more than 3"):
            c.JSON(http.StatusConflict, gin.H{"error": err.Error()})
        default:
            ctrl.logger.WithError(err).Error("update task failed")
            c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to update task"})
        }
        return
    }

    c.JSON(http.StatusOK, gin.H{"message": "task updated"})
}

// Delete godoc
// @Summary      Delete a task
// @Description  Deletes a task (owner only)
// @Tags         tasks
// @Security     BearerAuth
// @Param        id path string true "Task ID"
// @Success      204 "No Content"
// @Failure      401 {object} map[string]string "unauthorized"
// @Failure      403 {object} map[string]string "access denied"
// @Failure      404 {object} map[string]string "not found"
// @Router       /tasks/{id} [delete]
func (ctrl *TaskController) Delete(c *gin.Context) {
    taskID := c.Param("id")
    if taskID == "" {
        c.JSON(http.StatusBadRequest, gin.H{"error": "invalid task ID"})
        return
    }

    userID, _ := c.Get("userID")
    userIDStr := userID.(string)

    err := ctrl.taskService.Delete(c.Request.Context(), taskID, userIDStr)
    if err != nil {
        if strings.Contains(err.Error(), "not found") {
            c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
            return
        }
        if strings.Contains(err.Error(), "access denied") {
            c.JSON(http.StatusForbidden, gin.H{"error": err.Error()})
            return
        }
        ctrl.logger.WithError(err).Error("delete task failed")
        c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to delete task"})
        return
    }

    c.Status(http.StatusNoContent)
}