// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// RegisterRoutes is an autogenerated mock type for the RegisterRoutes type
type RegisterRoutes struct {
	mock.Mock
}

// RegisterRoutes provides a mock function with given fields: rg
func (_m *RegisterRoutes) RegisterRoutes(rg *gin.RouterGroup) {
	_m.Called(rg)
}

// NewRegisterRoutes creates a new instance of RegisterRoutes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterRoutes(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterRoutes {
	mock := &RegisterRoutes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
