// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Perlishnov/TODO_APP/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

// CountByUserAndStatus provides a mock function with given fields: ctx, userId, status
func (_m *TaskService) CountByUserAndStatus(ctx context.Context, userId string, status string) (int64, error) {
	ret := _m.Called(ctx, userId, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByUserAndStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (int64, error)); ok {
		return rf(ctx, userId, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = rf(ctx, userId, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userId, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, task
func (_m *TaskService) Create(ctx context.Context, task *models.Task) error {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Task) error); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, requestingUserID
func (_m *TaskService) Delete(ctx context.Context, id string, requestingUserID string) error {
	ret := _m.Called(ctx, id, requestingUserID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, requestingUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: ctx, id, requestingUserID
func (_m *TaskService) GetById(ctx context.Context, id string, requestingUserID string) (*models.Task, error) {
	ret := _m.Called(ctx, id, requestingUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Task, error)); ok {
		return rf(ctx, id, requestingUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Task); ok {
		r0 = rf(ctx, id, requestingUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, requestingUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter, userID
func (_m *TaskService) List(ctx context.Context, filter *models.TaskFilter, userID string) ([]models.Task, error) {
	ret := _m.Called(ctx, filter, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.TaskFilter, string) ([]models.Task, error)); ok {
		return rf(ctx, filter, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.TaskFilter, string) []models.Task); ok {
		r0 = rf(ctx, filter, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.TaskFilter, string) error); ok {
		r1 = rf(ctx, filter, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, task, requestingUserID
func (_m *TaskService) Update(ctx context.Context, task *models.Task, requestingUserID string) error {
	ret := _m.Called(ctx, task, requestingUserID)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Task, string) error); ok {
		r0 = rf(ctx, task, requestingUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
