// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Perlishnov/TODO_APP/internal/config"
	"github.com/Perlishnov/TODO_APP/internal/controller"
	"github.com/Perlishnov/TODO_APP/internal/dao"
	"github.com/Perlishnov/TODO_APP/internal/middleware"
	"github.com/Perlishnov/TODO_APP/internal/service"
	"github.com/Perlishnov/TODO_APP/internal/utils"
	"github.com/Perlishnov/TODO_APP/pkg/database"
	"github.com/sirupsen/logrus"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logger := provideLogger(configConfig)
	database, err := provideMongo(configConfig, logger)
	if err != nil {
		return nil, err
	}
	userDAO := dao.NewUserDAO(database, logger)
	jwtService := provideJWTService(configConfig)
	authService := service.NewAuthService(userDAO, jwtService, logger)
	authController := controller.NewAuthController(authService, logger)
	taskDAO := dao.NewTaskDAOMongo(database, logger)
	taskService := service.NewTaskService(taskDAO, jwtService, logger)
	taskController := controller.NewTaskController(taskService, logger)
	authMiddleware := middleware.NewAuthMiddleware(jwtService, logger)
	app := newApp(authController, taskController, authMiddleware, logger)
	return app, nil
}

// wire.go:

func provideLogger(cfg *config.Config) *logrus.Logger {
	return utils.NewLogger(cfg.LogLevel)
}

func provideMongo(cfg *config.Config, logger *logrus.Logger) (*mongo.Database, error) {
	return database.NewMongoConnection(cfg, logger)
}

func provideJWTService(cfg *config.Config) utils.JWTService {
	return utils.NewJWTUtil(cfg)
}

type App struct {
	AuthController *controller.AuthController
	TaskController *controller.TaskController
	AuthMiddleware *middleware.AuthMiddleware
	Logger         *logrus.Logger
}

func newApp(
	authCtrl *controller.AuthController,
	taskCtrl *controller.TaskController,
	authMW *middleware.AuthMiddleware,
	logger *logrus.Logger,
) *App {
	return &App{
		AuthController: authCtrl,
		TaskController: taskCtrl,
		AuthMiddleware: authMW,
		Logger:         logger,
	}
}
